# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    access_denied_url: access_denied
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Backend\UserBundle\Entity\User: 
            algorithm: sha1
            encode_as_base64: false
            iterations:       1

        Backend\CustomerBundle\Entity\Customer: 
            algorithm: sha1
            encode_as_base64: false
            iterations:       1
    
    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        administrators:
          entity: { class: BackendUserBundle:User}
        customers:
          entity: { class: BackendCustomerBundle:Customer}

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
         
        login:
            pattern:  ^/panel/login$
            #security: false
            anonymous:  ~

        secured_area:
            remember_me:
                key:      "%secret%"
                name: admin
                lifetime: 31536000 # 365 days in seconds
                path:     /panel
                domain:   ~
            pattern:    /panel
            provider: administrators
            form_login:
                check_path: /panel/login_check
                login_path: /panel/login
            logout:
                path: /panel/logout
                target: /panel/login
        
        customer_login:
            pattern:  ^/customer/login$
            #security: false
            anonymous:  ~
        
        customer_loginFront:
            pattern:  ^/customer/loginFront$
            #security: false
            anonymous:  ~
            
        customer:
            remember_me:
                key:      "%secret%"
                name: customer
                lifetime: 31536000 # 365 days in seconds
                path:     /customer
                domain:   ~
            access_denied_url: customer_access_denied
            pattern: /customer
            form_login:
                login_path: customer_login
                check_path: customer_auth
            provider: customers
            logout:
                path: customer_logout
                target: /


    access_control:
        - { path: ^/panel/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/customer/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/panel, roles: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/customer, roles: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }